param(
    [Parameter(Position = 0)]
    [ValidateSet("up", "down", "clean")]
    [string]$Command
)

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$RuntimeDir = Join-Path $ProjectRoot ".runtime"
$LogsDir = Join-Path $RuntimeDir "logs"
$PidsDir = Join-Path $RuntimeDir "pids"
$ComposeFile = Join-Path $ProjectRoot "docker-compose.dev.yml"
$BackendDir = Join-Path $ProjectRoot "backend"
$FrontendDir = Join-Path $ProjectRoot "frontend"
$AIWorkerDir = Join-Path $ProjectRoot "ai-worker"
$JdkDir = Join-Path $ProjectRoot "jdk-21.0.3+9"
$JdkZip = Join-Path $RuntimeDir "jdk-21.zip"
$JdkDownloadUrl = "https://api.adoptium.net/v3/binary/latest/21/ga/windows/x64/jdk/hotspot/normal/eclipse"

function Show-Usage {
    Write-Host "Usage: .\setup.ps1 <up|down|clean>" -ForegroundColor Cyan
    Write-Host "  up     Start Docker infra, backend, frontend, AI Worker; write logs to .runtime/logs/"
    Write-Host "  down   Stop backend/frontend/AI Worker and Docker infra; delete .runtime"
    Write-Host "  clean  Stop runtime, remove Docker containers/volumes/orphans, delete generated local artifacts"
}

function Ensure-RuntimeDirs {
    New-Item -ItemType Directory -Force $LogsDir, $PidsDir | Out-Null
}

function Test-PortAvailable([int]$Port) {
    $listener = $null
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        return $true
    }
    catch {
        return $false
    }
    finally {
        if ($listener) {
            $listener.Stop()
        }
    }
}

function Get-FreePort([int]$PreferredPort) {
    $port = $PreferredPort
    while ((-not (Test-PortAvailable $port)) -or ($script:ReservedPorts -contains $port)) {
        $port++
    }
    $script:ReservedPorts += $port
    return $port
}

function Read-PortsEnv {
    $portsFile = Join-Path $RuntimeDir "ports.env"
    if (-not (Test-Path $portsFile)) {
        return $null
    }

    $ports = [ordered]@{}
    foreach ($line in Get-Content $portsFile) {
        if ($line -match "^([^=]+)=(\d+)$") {
            $ports[$matches[1]] = [int]$matches[2]
        }
    }
    return $ports
}

function Set-RuntimePorts {
    $existingPorts = Read-PortsEnv
    $backendRunning = Get-ProcessFromPidFile "backend" $BackendDir
    $frontendRunning = Get-ProcessFromPidFile "frontend" $FrontendDir

    if ($existingPorts -and ($backendRunning -or $frontendRunning)) {
        $script:Ports = $existingPorts
    }
    else {
        $script:ReservedPorts = @()
        $infraPort = 7001
        $script:Ports = [ordered]@{
            FRONTEND_PORT      = Get-FreePort 3000
            BACKEND_PORT       = Get-FreePort 8080
            AI_WORKER_PORT     = Get-FreePort 8090
            ADMINER_PORT       = Get-FreePort $infraPort
            MINIO_CONSOLE_PORT = Get-FreePort ($infraPort + 1)
            REDISINSIGHT_PORT  = Get-FreePort ($infraPort + 2)
            RABBITMQ_UI_PORT   = Get-FreePort ($infraPort + 3)
            MARIADB_PORT       = Get-FreePort ($infraPort + 4)
            MINIO_API_PORT     = Get-FreePort ($infraPort + 5)
            REDIS_PORT         = Get-FreePort ($infraPort + 6)
            RABBITMQ_PORT      = Get-FreePort ($infraPort + 7)
        }
    }

    foreach ($entry in $script:Ports.GetEnumerator()) {
        Set-Item -Path "Env:$($entry.Key)" -Value $entry.Value
    }
}

function Write-PortsEnv {
    $portsFile = Join-Path $RuntimeDir "ports.env"
    $script:Ports.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" } | Set-Content -Path $portsFile -Encoding utf8
    Write-Host "Ports written to .runtime/ports.env" -ForegroundColor Green
}

function Write-FrontendEnv {
    $frontendEnvFile = Join-Path $FrontendDir ".env.local"
    @(
        "# Auto-generated by setup.ps1. Do not edit manually."
        "NEXT_PUBLIC_API_URL=http://localhost:$($script:Ports.BACKEND_PORT)"
        "NEXT_PUBLIC_AI_WORKER_URL=http://localhost:$($script:Ports.AI_WORKER_PORT)"
    ) | Set-Content -Path $frontendEnvFile -Encoding utf8
    Write-Host "Frontend env written to frontend/.env.local" -ForegroundColor Green
}

function Remove-RuntimeArtifacts {
    if (Test-Path $RuntimeDir) {
        Remove-Item -Recurse -Force $RuntimeDir
    }
}

function Test-CommandExists([string]$CommandName) {
    return [bool](Get-Command $CommandName -ErrorAction SilentlyContinue)
}

function Assert-CommandExists([string]$CommandName, [string]$InstallHint) {
    if (-not (Test-CommandExists $CommandName)) {
        throw "$CommandName not found. Install it first: $InstallHint"
    }
}

function Get-JavaMajorVersion {
    $javaCommand = Get-Command java -ErrorAction SilentlyContinue
    if (-not $javaCommand) {
        return $null
    }

    $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
    $startInfo.FileName = $javaCommand.Source
    $startInfo.Arguments = "-version"
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true
    $startInfo.UseShellExecute = $false

    $process = [System.Diagnostics.Process]::Start($startInfo)
    $output = $process.StandardOutput.ReadToEnd() + $process.StandardError.ReadToEnd()
    $process.WaitForExit()

    if ($output -match 'version "(\d+)') {
        return [int]$matches[1]
    }

    return $null
}

function Expand-LocalJdk {
    if (Test-Path (Join-Path $JdkDir "bin\java.exe")) {
        return
    }

    Remove-Item -Recurse -Force $JdkDir -ErrorAction SilentlyContinue
    Write-Host "Downloading JDK 21 to project-local runtime cache..." -ForegroundColor Cyan
    Invoke-WebRequest -Uri $JdkDownloadUrl -OutFile $JdkZip

    $extractDir = Join-Path $RuntimeDir "jdk-extract"
    Remove-Item -Recurse -Force $extractDir -ErrorAction SilentlyContinue
    Expand-Archive -Path $JdkZip -DestinationPath $extractDir -Force

    $extractedJdk = Get-ChildItem -Path $extractDir -Directory | Where-Object { Test-Path (Join-Path $_.FullName "bin\java.exe") } | Select-Object -First 1
    if (-not $extractedJdk) {
        throw "Downloaded JDK archive did not contain bin\java.exe"
    }

    Move-Item -Path $extractedJdk.FullName -Destination $JdkDir
    Remove-Item -Recurse -Force $extractDir
    Remove-Item -Force $JdkZip -ErrorAction SilentlyContinue
    Write-Host "JDK 21 ready: $JdkDir" -ForegroundColor Green
}

function Ensure-Java21 {
    if (Test-Path (Join-Path $JdkDir "bin\java.exe")) {
        return
    }

    $major = Get-JavaMajorVersion
    if ($major -ge 21) {
        return
    }

    Expand-LocalJdk
}

function Ensure-FrontendDependencies {
    $nodeModules = Join-Path $FrontendDir "node_modules"
    if (Test-Path $nodeModules) {
        return
    }

    Write-Host "Installing frontend dependencies with npm install..." -ForegroundColor Cyan
    Push-Location $FrontendDir
    try {
        npm install
    }
    finally {
        Pop-Location
    }
}

function Ensure-Prerequisites {
    Assert-CommandExists "docker" "Docker Desktop: https://www.docker.com/products/docker-desktop/"
    Assert-CommandExists "node" "Node.js LTS: https://nodejs.org/"
    Assert-CommandExists "npm" "Node.js LTS includes npm: https://nodejs.org/"
    Assert-CommandExists "python" "Python 3: https://www.python.org/downloads/windows/"

    docker info | Out-Null
    Ensure-Java21
    Ensure-FrontendDependencies
}

function New-LoggedCommand([string]$Command, [string]$LogPath) {
    return '[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false); [Console]::InputEncoding = [System.Text.UTF8Encoding]::new($false); $OutputEncoding = [System.Text.UTF8Encoding]::new($false); $env:PYTHONUTF8 = ''1''; $env:PYTHONIOENCODING = ''utf-8''; $ErrorActionPreference = ''Continue''; & { ' + $Command + ' } 2>&1 | Out-File -FilePath ''' + $LogPath + ''' -Encoding utf8'
}

function Get-PidFilePath([string]$Name) {
    return Join-Path $PidsDir "$Name.pid"
}

function Get-MetaFilePath([string]$Name) {
    return Join-Path $PidsDir "$Name.json"
}

function Write-ProcessMetadata([string]$Name, [System.Diagnostics.Process]$Process, [string]$WorkingDirectory) {
    [ordered]@{
        pid = $Process.Id
        name = $Name
        workingDirectory = $WorkingDirectory
        startTime = $Process.StartTime.ToUniversalTime().ToString("o")
    } | ConvertTo-Json | Set-Content -Path (Get-MetaFilePath $Name) -Encoding utf8
}

function Get-ProcessFromPidFile([string]$Name, [string]$ExpectedWorkingDirectory) {
    $pidFile = Get-PidFilePath $Name
    $metaFile = Get-MetaFilePath $Name
    if ((-not (Test-Path $pidFile)) -or (-not (Test-Path $metaFile))) {
        return $null
    }

    $rawPid = Get-Content $pidFile -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $rawPid) {
        Remove-Item $pidFile, $metaFile -Force -ErrorAction SilentlyContinue
        return $null
    }

    $process = Get-Process -Id ([int]$rawPid) -ErrorAction SilentlyContinue
    if (-not $process) {
        Remove-Item $pidFile, $metaFile -Force -ErrorAction SilentlyContinue
        return $null
    }

    $metadata = Get-Content $metaFile -Raw -ErrorAction SilentlyContinue | ConvertFrom-Json
    if ((-not $metadata) -or ($metadata.name -ne $Name) -or ($metadata.workingDirectory -ne $ExpectedWorkingDirectory)) {
        throw "Refusing to use invalid PID metadata for $Name. Run setup.ps1 clean only after inspecting .runtime/pids/."
    }

    $metadataStartTime = [datetime]::Parse($metadata.startTime).ToUniversalTime()
    $processStartTime = $process.StartTime.ToUniversalTime()
    if ([math]::Abs(($processStartTime - $metadataStartTime).TotalSeconds) -gt 1) {
        throw "Refusing to stop $Name because PID $($process.Id) was reused by another process."
    }

    return $process
}

function Stop-ProcessTree([int]$ProcessId) {
    $children = Get-CimInstance Win32_Process -Filter "ParentProcessId=$ProcessId" -ErrorAction SilentlyContinue
    foreach ($child in $children) {
        Stop-ProcessTree $child.ProcessId
    }

    Stop-Process -Id $ProcessId -Force -ErrorAction SilentlyContinue
}

function Stop-RuntimeProcess([string]$Name, [string]$ExpectedWorkingDirectory) {
    $process = Get-ProcessFromPidFile $Name $ExpectedWorkingDirectory

    if ($process) {
        Write-Host "Stopping $Name (PID $($process.Id))..." -ForegroundColor Yellow
        Stop-ProcessTree $process.Id
    }
    else {
        Write-Host "Stopping $Name... not running." -ForegroundColor DarkYellow
    }

    Remove-Item (Get-PidFilePath $Name), (Get-MetaFilePath $Name) -Force -ErrorAction SilentlyContinue
}

function Get-BackendLocalEnvCommand {
    $envFile = Join-Path $BackendDir ".env.local"
    if (-not (Test-Path $envFile)) {
        return ""
    }

    $commands = @()
    foreach ($line in Get-Content $envFile) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#") -or -not $trimmed.Contains("=")) {
            continue
        }

        $parts = $trimmed.Split("=", 2)
        $name = $parts[0].Trim()
        $value = $parts[1].Trim().Replace("'", "''")
        if ($name -match "^[A-Za-z_][A-Za-z0-9_]*$") {
            $commands += '$env:' + $name + " = '" + $value + "'; "
        }
    }

    return ($commands -join "")
}

function Start-Backend {
    $running = Get-ProcessFromPidFile "backend" $BackendDir
    if ($running) {
        Write-Host "Backend already running (PID $($running.Id)); keeping existing process." -ForegroundColor Green
        return
    }

    $backendLog = Join-Path $LogsDir "backend.log"
    $backendPid = Join-Path $PidsDir "backend.pid"

    $javaSetup = ""
    if (Test-Path $JdkDir) {
        $javaSetup = '$env:JAVA_HOME = ''' + $JdkDir + '''; $env:PATH = $env:JAVA_HOME + ''\bin;'' + $env:PATH; '
    }

    $envSetup = '$env:BACKEND_PORT = ''' + $script:Ports.BACKEND_PORT + '''; ' +
        '$env:DB_PORT = ''' + $script:Ports.MARIADB_PORT + '''; ' +
        '$env:REDIS_PORT = ''' + $script:Ports.REDIS_PORT + '''; ' +
        '$env:RABBITMQ_PORT = ''' + $script:Ports.RABBITMQ_PORT + '''; ' +
        '$env:MINIO_ENDPOINT = ''http://localhost:' + $script:Ports.MINIO_API_PORT + '''; '

    $command = $javaSetup + $envSetup + (Get-BackendLocalEnvCommand) + '.\mvnw.cmd spring-boot:run'
    $loggedCommand = New-LoggedCommand $command $backendLog
    $process = Start-Process powershell `
        -WorkingDirectory $BackendDir `
        -ArgumentList @("-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", $loggedCommand) `
        -PassThru `
        -WindowStyle Hidden

    Set-Content -Path $backendPid -Value $process.Id
    Write-ProcessMetadata "backend" $process $BackendDir
    Write-Host "Backend starting (PID $($process.Id)); logs: .runtime/logs/backend.log" -ForegroundColor Green
}

function Start-Frontend {
    $running = Get-ProcessFromPidFile "frontend" $FrontendDir
    if ($running) {
        Write-Host "Frontend already running (PID $($running.Id)); keeping existing process." -ForegroundColor Green
        return
    }

    $frontendLog = Join-Path $LogsDir "frontend.log"
    $frontendPid = Join-Path $PidsDir "frontend.pid"
    $frontendCommand = '$env:NO_COLOR = ''1''; $env:FORCE_COLOR = ''0''; $env:TERM = ''dumb''; $env:NEXT_TELEMETRY_DISABLED = ''1''; ' +
        '$env:NEXT_PUBLIC_API_URL = ''http://localhost:' + $script:Ports.BACKEND_PORT + '''; ' +
        '$env:NEXT_PUBLIC_AI_WORKER_URL = ''http://localhost:' + $script:Ports.AI_WORKER_PORT + '''; ' +
        'npm run dev -- --port ' + $script:Ports.FRONTEND_PORT

    $loggedCommand = New-LoggedCommand $frontendCommand $frontendLog
    $process = Start-Process powershell `
        -WorkingDirectory $FrontendDir `
        -ArgumentList @("-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", $loggedCommand) `
        -PassThru `
        -WindowStyle Hidden

    Set-Content -Path $frontendPid -Value $process.Id
    Write-ProcessMetadata "frontend" $process $FrontendDir
    Write-Host "Frontend starting (PID $($process.Id)); logs: .runtime/logs/frontend.log" -ForegroundColor Green
}

function Start-AIWorker {
    $running = Get-ProcessFromPidFile "ai-worker" $AIWorkerDir
    if ($running) {
        Write-Host "AI Worker already running (PID $($running.Id)); keeping existing process." -ForegroundColor Green
        return
    }

    $aiLog = Join-Path $LogsDir "ai-worker.log"
    $aiPid = Join-Path $PidsDir "ai-worker.pid"
    $command = 'if (-not (Test-Path ''venv'')) { python -m venv venv }; ' +
        '.\venv\Scripts\python.exe -m pip --disable-pip-version-check install -r requirements.txt | Out-Null; ' +
        '$env:BACKEND_URL = ''http://localhost:' + $script:Ports.BACKEND_PORT + '''; ' +
        '$env:MINIO_URL = ''localhost:' + $script:Ports.MINIO_API_PORT + '''; ' +
        '.\venv\Scripts\python.exe service.py --port ' + $script:Ports.AI_WORKER_PORT +
        ' --backend-url ''http://localhost:' + $script:Ports.BACKEND_PORT + ''' --minio-url ''localhost:' + $script:Ports.MINIO_API_PORT + ''''

    $loggedCommand = New-LoggedCommand $command $aiLog
    $process = Start-Process powershell `
        -WorkingDirectory $AIWorkerDir `
        -ArgumentList @("-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", $loggedCommand) `
        -PassThru `
        -WindowStyle Hidden

    Set-Content -Path $aiPid -Value $process.Id
    Write-ProcessMetadata "ai-worker" $process $AIWorkerDir
    Write-Host "AI Worker starting (PID $($process.Id)); logs: .runtime/logs/ai-worker.log" -ForegroundColor Green
}

function Remove-AnsiCodes([string]$Text) {
    return $Text -replace "`e\[[0-9;]*[A-Za-z]", ""
}

function Invoke-DockerComposePsJson {
    $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
    $startInfo.FileName = "docker"
    $startInfo.Arguments = "compose -f `"$ComposeFile`" ps --format json"
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true
    $startInfo.UseShellExecute = $false

    $process = [System.Diagnostics.Process]::Start($startInfo)
    $stdout = $process.StandardOutput.ReadToEnd()
    $process.StandardError.ReadToEnd() | Out-Null
    $process.WaitForExit()

    if ($process.ExitCode -ne 0) {
        return $null
    }

    return $stdout
}

function Wait-InfraReady([int]$TimeoutSeconds) {
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        $statusJson = Invoke-DockerComposePsJson
        if ($statusJson) {
            $services = @($statusJson -split "`r?`n" | Where-Object { $_.Trim() } | ForEach-Object { $_ | ConvertFrom-Json })
            if ($services.Count -ge 6) {
                $notReady = @($services | Where-Object {
                    $_.State -ne "running" -or ($_.Health -and $_.Health -ne "healthy")
                })
                if ($notReady.Count -eq 0) {
                    return $true
                }
            }
        }
        Start-Sleep -Seconds 2
    }
    return $false
}

function Start-Infra {
    $dockerLog = Join-Path $LogsDir "docker.log"
    Write-Host "Starting Docker infrastructure..." -ForegroundColor Cyan
    docker compose -f $ComposeFile up -d | Tee-Object -FilePath $dockerLog
    if (-not (Wait-InfraReady 90)) {
        "`n=== Docker Compose Status: TIMEOUT waiting for all services healthy ===" | Out-File -FilePath $dockerLog -Append -Encoding utf8
    }
    else {
        "`n=== Docker Compose Status: all services running/healthy ===" | Out-File -FilePath $dockerLog -Append -Encoding utf8
    }
    docker compose -f $ComposeFile ps | Out-File -FilePath $dockerLog -Append -Encoding utf8
    "`n=== Docker Compose Logs ===" | Out-File -FilePath $dockerLog -Append -Encoding utf8
    $composeLogs = docker compose -f $ComposeFile logs --no-color
    (Remove-AnsiCodes ($composeLogs -join "`n")) | Out-File -FilePath $dockerLog -Append -Encoding utf8
}

function Stop-Infra {
    if (Test-Path $ComposeFile) {
        Write-Host "Stopping Docker infrastructure..." -ForegroundColor Cyan
        docker compose -f $ComposeFile down
    }
}

function Clean-Infra {
    if (Test-Path $ComposeFile) {
        Write-Host "Removing Docker containers, volumes, and orphans for this compose project..." -ForegroundColor Yellow
        docker compose -f $ComposeFile down -v --remove-orphans
    }
}

function Remove-BackendTarget {
    $targetDir = Join-Path $BackendDir "target"
    if (Test-Path $targetDir) {
        Remove-Item -Recurse -Force $targetDir
        Write-Host "Backend target removed." -ForegroundColor Green
    }
}

function Remove-AIWorkerVenv {
    $venvDir = Join-Path $AIWorkerDir "venv"
    if (Test-Path $venvDir) {
        Remove-Item -Recurse -Force $venvDir
        Write-Host "AI Worker venv removed." -ForegroundColor Green
    }
}

function Remove-FrontendNodeModules {
    $nodeModules = Join-Path $FrontendDir "node_modules"
    if (Test-Path $nodeModules) {
        Remove-Item -Recurse -Force $nodeModules
        Write-Host "Frontend node_modules removed." -ForegroundColor Green
    }
}

function Remove-FrontendNextBuild {
    $nextBuild = Join-Path $FrontendDir ".next"
    if (Test-Path $nextBuild) {
        Remove-Item -Recurse -Force $nextBuild
        Write-Host "Frontend .next removed." -ForegroundColor Green
    }
}

function Remove-LocalJdk {
    if (Test-Path $JdkDir) {
        Remove-Item -Recurse -Force $JdkDir
        Write-Host "Local JDK removed." -ForegroundColor Green
    }
}

if (-not $Command) {
    Show-Usage
    exit 1
}

switch ($Command) {
    "up" {
        Ensure-RuntimeDirs
        Ensure-Prerequisites
        Set-RuntimePorts
        Write-PortsEnv
        Write-FrontendEnv
        Start-Infra
        Start-Backend
        Start-Frontend
        Start-AIWorker
        Write-Host "FireSafe runtime started." -ForegroundColor Green
        Write-Host "Logs: .runtime/logs/" -ForegroundColor Cyan
    }
    "down" {
        Ensure-RuntimeDirs
        Stop-RuntimeProcess "ai-worker" $AIWorkerDir
        Stop-RuntimeProcess "frontend" $FrontendDir
        Stop-RuntimeProcess "backend" $BackendDir
        Stop-Infra
        Remove-RuntimeArtifacts
        Write-Host "FireSafe runtime stopped. Runtime artifacts removed." -ForegroundColor Green
    }
    "clean" {
        Ensure-RuntimeDirs
        Stop-RuntimeProcess "ai-worker" $AIWorkerDir
        Stop-RuntimeProcess "frontend" $FrontendDir
        Stop-RuntimeProcess "backend" $BackendDir
        Clean-Infra
        Remove-BackendTarget
        Remove-AIWorkerVenv
        Remove-FrontendNodeModules
        Remove-FrontendNextBuild
        Remove-LocalJdk
        Remove-RuntimeArtifacts
        Write-Host "FireSafe runtime cleaned. Runtime artifacts removed." -ForegroundColor Green
    }
}
