INSERT INTO roles (name)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN');

INSERT INTO roles (name)
SELECT 'ROLE_VIEWER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_VIEWER');

DELETE ur FROM user_roles ur
JOIN roles r ON ur.role_id = r.id
WHERE r.name = 'ROLE_OPERATOR';

DELETE FROM roles WHERE name = 'ROLE_OPERATOR';
