listeners.tcp.default = 5672
management.tcp.port = 15672
management.load_definitions = /etc/rabbitmq/definitions.json

vm_memory_high_watermark.relative = 0.4
disk_free_limit.absolute = 1GB

heartbeat = 60
channel_max = 2047
consumer_timeout = 1800000

default_queue_type = classic

prometheus.tcp.port = 15692

log.console = true
log.console.level = info
log.file.level = info
